### ISSUE TITLE
Typing "null" unindents a line. (#86 not fixed)

### ISSUE THREAD

**Issue by sarahkittyy** [JustusAdam/language-haskell#100]
Issue #86 is not fixed for me.

VSCode version:
```
1.40.0-insider
31f577ec88dc96ad2028699fb597b19022224b46
x64
```

**Comment by sarahkittyy** [comment]
This even works if `haskell.indentationRules.enabled` is `false`.

**Comment by robrix** [comment]
Looks like there hasn’t been a release since #86 was closed.

**Comment by JustusAdam** [comment]
I think I have a fix for this. I have not been able to test and push it yet.

**Comment by konn** [comment]
Is there any progress? I am (and actually my colleagues are) suffering from this issue. Is there any tentative workaround?

**Comment by JustusAdam** [comment]
I am so sorry, I forgot to publish. You should be fine now.

**Comment by konn** [comment]
Thanks!

**Comment by robrix** [comment]
@JustusAdam Thank you so much! ❤️
