### ISSUE TITLE
No syntax highlighting for prelude functions

### ISSUE THREAD

**Issue by patrickaldis** [JustusAdam/language-haskell#101]
Plugin doesn't seem to be highlighting functions from standard prelude. After using hie on atom, and looking at some other sample screenshots I'm pretty sure these should be highlighted.

Highlighting looks like this:
![image](https://user-images.githubusercontent.com/46719614/69064815-a3176880-0a16-11ea-8d70-064236e51518.png)

**Comment by JustusAdam** [comment]
Thank you for bringing this issue up, but this was a deliberate decision made in #11. As it is rather common for people to use custom preludes and also the contents of the actual prelude changes between releases, we have decided to *remove* highlighting for prelude functions.
