### ISSUE TITLE
Highlighting errors in multi-line type aliases

### ISSUE THREAD

**Issue by worm2fed** [JustusAdam/language-haskell#111]
![image](https://user-images.githubusercontent.com/6579275/79107527-301fdd00-7d7d-11ea-8e27-a2d6d44342a8.png)
types has no highlighting if there more then one line in equation
and the type operator in the first line has different color then in the others one

**Comment by worm2fed** [comment]
@JustusAdam I've noticed that the name was changed.

In my case it's not about "Highlighting errors in multi-line type aliases" whether about "Highlighting multi-line types" (not only aliases)

**Comment by JustusAdam** [comment]
The example you posted was specifically with `type`, is there another case where this same issue occurs?

**Comment by worm2fed** [comment]
oh. sorry
dunno what happened to me yesterday. gonna take some rest)

**Comment by JustusAdam** [comment]
It's all right. The good news is I think I have a fix to this issue already ;)

**Comment by worm2fed** [comment]
great! thanks

**Comment by worm2fed** [comment]
Hi. I've updated the extension, but...
![image](https://user-images.githubusercontent.com/6579275/79957306-0c9a1800-848a-11ea-93ba-1ae8ae0da280.png)
it's not working at all... maybe I made a mistake?

**Comment by JustusAdam** [comment]
A bit of patience please, I haven't released the changes yet.
I am planning to publish a pretty big bug-fixing release in the next few days ;)

**Comment by JustusAdam** [comment]
Or did you pull the development branch?

**Comment by worm2fed** [comment]
no, master..

but. then i've removed extension and installed it again from vs market... nothing
seems very strange

**Comment by worm2fed** [comment]
seems working after manual removing extension directory form vs code

**Comment by JustusAdam** [comment]
A that's good news. :+1:

**Comment by JustusAdam** [comment]
It's published. Let me know if you have any issues with the new version
