### ISSUE TITLE
Scoping Syntax Suggestions

### ISSUE THREAD

**Issue by johnxllis** [JustusAdam/language-haskell#12]
When I type `module MyModule where` and then tab or enter, it attempts the `name = value` completion which has to be deleted before moving on. Adding a space after `where` keeps this from happening but then I have an extra space character in my source file.

Is there a way to make this completion context aware and not try this completion when on the same line as `module`?

If possible, I'd be happy to make the change and submit a pull.

**Comment by JustusAdam** [comment]
I don't think so.

If you look at the [documentation](https://code.visualstudio.com/Docs/customization/userdefinedsnippets#_creating-your-own-snippets) it says that the prefix is used to select the snippet from IntelliSense and tab completion.
As far as I know both systems work with a single words, aka a string of word characters, meaning the trigger can't be more complex than a single word. Sorry.

If you're worried about extra spaces though, there's a setting in vscode `files.trimTrailingWhitespace` which automatically removes trailing whitespace in your source files on save. 😉

**Comment by johnxllis** [comment]
Thanks for looking into it. I enabled `files.trimTrailingWhitespace` which eliminates my quibble with the extra space. Cool! Thanks for your help.
