### ISSUE TITLE
Regresion: comments on records are not highlighted properly

### ISSUE THREAD

**Issue by emlautarom1** [JustusAdam/language-haskell#121]
Only the last comment is highlighted properly while all the other ones are displayed as plain text

![comments](https://user-images.githubusercontent.com/31224949/80319828-0dfc7500-87e9-11ea-9647-dc70f76488b0.png)

**Comment by sheaf** [comment]
This seems to be due to the comma. If you put the comma at the start of the next line instead, it highlights OK.

**Comment by emlautarom1** [comment]
Indeed, this fixes the issue. Sadly I just "can't" put the comma in the next line since I'm using [ormolu](https://github.com/tweag/ormolu) as my code formatter and this is the way it handles records.

**Comment by JustusAdam** [comment]
Thank you for reporting this. 👍  Will be fixed in the next release.

**Comment by sheaf** [comment]
This issue doesn't seem to be limited to records:
![comment_highlighting](https://user-images.githubusercontent.com/1297748/80328956-17b1c700-8841-11ea-8221-1f11c7bcf555.png)

**Comment by sheaf** [comment]
Bisecting shows that 562e08d was responsible for this issue.

**Comment by sheaf** [comment]
Fixed in 8ee07b6.
