### ISSUE TITLE
Incorrect substitutions

### ISSUE THREAD

**Issue by rakesh-k** [JustusAdam/language-haskell#13]
Having tough time using it under visual studio code. It randomly inserts this string at places:

`<no location info>: Expected a span: "<module-name/filepath>" <start line> <start column> <end line> <end column> "<sample string>"`

Removing it and correcting the code slows me down heavily. Wondering if I am not setup right?

**Comment by JustusAdam** [comment]
I have never seen this error ... 
Are you sure its this extension that's causing it?

Do you have any steps to recreate the issue?

**Comment by metaleap** [comment]
Sounds like something Intero emits: https://duckduckgo.com/?q=%22Expected+a+span%3A%22 so possibly a Haskero issue
