### ISSUE TITLE
Constructor just before parantheses not highlighted

### ISSUE THREAD

**Issue by Gerhood** [JustusAdam/language-haskell#151]
See attached screenshot.
Can be reproduced with any theme that generally makes a distinction with constructors. Version is 3.0.3.
![Highlighting](https://user-images.githubusercontent.com/17947189/80944117-10faf500-8de9-11ea-8e04-90cb51f7df9e.png)

**Comment by sheaf** [comment]
Thanks for the bug report. The source of the problem is the same as #122, and it has been fixed in commit 8424407.

New release should be coming soon (still a few bugs to iron out).
