### ISSUE TITLE
Unconstrained existential types break syntax highlighting

### ISSUE THREAD

**Issue by fatho** [JustusAdam/language-haskell#153]
Since a recent version of the extension, code like

```haskell
data Foo = forall x. Bar x
```

breaks syntax highlighting for the remainder of the file:

![image](https://user-images.githubusercontent.com/3857449/80966513-f3438500-8e14-11ea-987e-8c7dd3ece9db.png)

Adding an empty constraint to the existential like so

```haskell
data Foo = forall x. () => Bar x
```

makes it work as intended:

![image](https://user-images.githubusercontent.com/3857449/80966609-1bcb7f00-8e15-11ea-8cdf-97413422f293.png)

This might be related to https://github.com/JustusAdam/language-haskell/issues/39.

**Comment by sheaf** [comment]
Thank you for the bug report.

Indeed the fix in 95f1e01 for #39 proceeds by looking for the next `=>`, so predictably fails when there is no such arrow.

I've fixed this in commit 75b2c44 and added a test case in `T0153`. I've reverted to a simpler approach which will avoid this problem, but which might run into issues highlighting things correctly over multiple lines (a bit of a general limitation of the the TextMate grammars used in VS Code).
