### ISSUE TITLE
Issues when recognizing white-spaces in record types

### ISSUE THREAD

**Issue by fabioluz** [JustusAdam/language-haskell#155]
Hi,

The extension works great for record types. 

![image](https://user-images.githubusercontent.com/5049361/81016056-20ecf600-8e36-11ea-928e-1f72e9564e32.png)

However, it does not recognize it well if I add blank spaces before "::". For example:

![image](https://user-images.githubusercontent.com/5049361/81015858-cbb0e480-8e35-11ea-9760-0a67a6d9bd87.png)

See that "email" is turned into white once I add spaces to make it fit with "password". The "::" and the type are not recognized as symbols. 

![image](https://user-images.githubusercontent.com/5049361/81016142-48dc5980-8e36-11ea-9403-5974c4181c4c.png)

I tried to check the regex and it seems that it is expecting white-spaces before "::" so I couldn't find out why this is happening.

Any ideas?
Thank you!

**Comment by sheaf** [comment]
Yep! This has since been fixed, see #155 and #118.

Thanks for reporting the bug.
