### ISSUE TITLE
Highlighting inside pragmas

### ISSUE THREAD

**Issue by sheaf** [JustusAdam/language-haskell#157]
Some pragmas would benefit from different highlighting inside the pragma. The most useful in my opinion would be to highlight the type signature in a specialise pragma, and perhaps also highlighting in rules.

```haskell
{-# SPECIALIZE [0] hammeredLookup :: [(Widget, value)] -> Widget -> value #-}

{-# SPECIALISE INLINE (!:) :: Arr (a, b) -> Int -> (a, b) #-} 

instance (Eq a) => Eq (Foo a) where {
   {-# SPECIALIZE instance Eq (Foo [(Int, Bar)]) #-}
  -- ... usual stuff ...
 }
```

**Comment by sheaf** [comment]
@JustusAdam 
I'm having trouble with highlighting a type signature inside a pragma, for the same reason that there are still issues highlighting within a LiquidHaskell block: if I include `#type_signature` or `$self` then it starts shifting the end so that the highlighting keeps going after the end of the block.

See test `CommentLike` which is currently failing. For the LiquidHaskell one, you'll notice it highlights the closing `@-` as a type operator, which is why I had a workaround to avoid a type operator gobbling up `@-` when it is followed by `}`. However I realised that didn't completely fix it because content later on on the same line is still highlighted as a LiquidHaskell block (this explains why I reverted that workaround in 8bbb096).

Do you have any ideas?

**Comment by JustusAdam** [comment]
Well, if `@` and `#` are legal characters in operators, I don;t think we have a choice but to exclude them directly

**Comment by sheaf** [comment]
Yes, that's true and you are right to point it out. What was concerning me was that, even with such an exclusion in place, for some reason the LiquidHaskell scope was still extending past the end of the block. I need to revisit it and understand why that was happening

**Comment by JustusAdam** [comment]
I took a stab at it and it seems to pass the test case. It doesn't pass the whole file, because I don't know what the `{-$` rules are supposed to do. I've not seen that kind of annotation and so I'm not familiar with its semantics and how it should work. But I'd expect a simple adjustment to the comment rule, i.e. `begin: '{-\$?'` should do the trick no?

**Comment by sheaf** [comment]
I'm not sure changing to `type_signature` for LiquidHaskell is a good idea, as other kinds of annotations are supported, e.g. defining types for use in other contexts:

```haskell
{-@ type NonEmpty a = {v:[a] | 0 < len v } @-}
```

**Comment by JustusAdam** [comment]
It does though. At least for me those test cases fail.

Well, then perhaps we should only trigger upon encountering `::`

**Comment by sheaf** [comment]
Oh, the scope was just missing the `.haskell` in the test case, that's all. Nothing to worry about

**Comment by sheaf** [comment]
Sorry but the latest changes to the LiquidHaskell constitute a regression. Beforehand, everything was highlighted in LiquidHaskell annotations (but there was a problem with highlighting past the ending, which is not something I expect you see in source code anyway). Now however, only type signatures are highlighted, not type declarations as above.

**Comment by sheaf** [comment]
OK thanks to your fix for `start_type_signature` I was able to get `SPECIALISE` pragmas to highlight correctly. So I'll close this ticket now, although we could still support highlighting for `RULES` pragmas.
