### ISSUE TITLE
Broken highlighting for record fields in v3.1.0?

### ISSUE THREAD

**Issue by vaclavsvejcar** [JustusAdam/language-haskell#160]
Some of my record definitions have broken highlighting, even after upgrading to `3.1.0` (see screenshot). I really cannot figure out how to reproduce this, it seems to just occur randomly. Any hints what could be the root cause for this?

<img width="600" alt="Snímek obrazovky 2020-05-11 v 20 51 49" src="https://user-images.githubusercontent.com/5843430/81599994-41362b00-93c9-11ea-98fd-9a277d0ee042.png">

**Comment by JustusAdam** [comment]
Yes, very sorry. I made an error during publishing and actually none of the fixes were included. I think I fixed it now and published 3.2.0. Let me know if the issues persist

**Comment by vaclavsvejcar** [comment]
Works like a charm now, thanks a lot! 👍
