### ISSUE TITLE
Incorrect highlighting for multiline function type

### ISSUE THREAD

**Issue by dansanduleac** [JustusAdam/language-haskell#162]
Using the brittany formatter puts the `::` type on the 2nd line for really long type definitions.

Unfortunately the syntax breaks in that case, it doesn't assign any special textmate scope to the type declaration anymore.

![image](https://user-images.githubusercontent.com/222827/82706400-63edfc80-9c71-11ea-98bf-7f6ee643b29c.png)

If I pull the `::` onto the first line, then it works again.

![image](https://user-images.githubusercontent.com/222827/82706486-9b5ca900-9c71-11ea-80a4-c3268d1d727d.png)

**Comment by sheaf** [comment]
Thanks for the bug report. Unfortunately, to my knowledge this can't be fixed because of the way syntax highlighting works in VS Code (using TextMate grammars), because there's no way to backtrack after looking ahead to a new line. See also issues #27 and #60.
