### ISSUE TITLE
could not find module error

### ISSUE THREAD

**Issue by traptw1thin** [JustusAdam/language-haskell#166]
the statement: `import SomeModule` is highlighted and it says: 

> Could not find module `SomeModule'
> Use -v (or `:set -v` in ghci) to see a list of the files searched for.

However, `SomeModule.hs` is in the same directory and the code compiles just fine. The full header of the file is, for instance:

```
module HW3 (module HW3, module SomeModule) where

import SomeModule
```

**Comment by JustusAdam** [comment]
Hi, this is not an issue with this extension. We only do static code highlighting. You must be using some other ide extension as well which is generating the warning. Sorry.
