### ISSUE TITLE
Further suggestions and questions

### ISSUE THREAD

**Issue by metaleap** [JustusAdam/language-haskell#17]
For `keyword.control.haskell`: where you have [(do|if|then|else)](https://github.com/JustusAdam/language-haskell/blob/master/syntaxes/haskell.tmLanguage#L320) I'd suggest (in the same spirit of those 2 concepts) to also add:

`mdo`, `case`, `of`

**Comment by metaleap** [comment]
Don't know what [(?&lt;conid&gt;[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}']*(\.\g&lt;conid&gt;)?)](https://github.com/JustusAdam/language-haskell/blob/master/syntaxes/haskell.tmLanguage#L768) does, but that looks like embedded tags (HsColour or such), if so, does the 2nd one need a closing `/`? Sorry just occurred to me as I was browsing all the scopes you're emitting for my "Haskell-first-class colour theme" ;) ignore if I'm wrong

**Comment by metaleap** [comment]
I find both a `constant.language.unit.haskell` and a `support.constant.unit.haskell` .. are these exactly the same purposes? Will cover both in 1 case for now, but just curious

**Comment by JustusAdam** [comment]
Hmm, the control one makes sense to me.

About the `condid` thing, I don't know. I didn't write that one 😹

**Comment by JustusAdam** [comment]
Maybe it would be useful to add some more comments to the code explaining what things do ...

**Comment by sheaf** [comment]
Closing as the suggested keywords have since been added.
