### ISSUE TITLE
['|'] or any list with '|' as its first element stops syntax highlighting for the rest of the document.

### ISSUE THREAD

**Issue by gorilskij** [JustusAdam/language-haskell#170]
This is only a problem with che character `'|'` as the first element in a list literal, i imagine it has something to do with comprehension literals?

An example:
<img width="623" alt="Schermata 2020-07-25 alle 15 47 10" src="https://user-images.githubusercontent.com/43991400/88458399-1c146d00-ce8e-11ea-8fae-f830d37064fa.png">
... the rest of the file is white.

Doesn't cause a problem when the list is recognized as an error.
<img width="482" alt="Schermata 2020-07-25 alle 15 50 25" src="https://user-images.githubusercontent.com/43991400/88458468-904f1080-ce8e-11ea-90e0-e42b265bd603.png">

For some reason this (erroneous) pattern fixes the highlighting (it then continues as normal).
Note that `| ]` (with a space) doesn't work.
<img width="135" alt="Schermata 2020-07-25 alle 15 57 04" src="https://user-images.githubusercontent.com/43991400/88458601-7f52cf00-ce8f-11ea-9c85-49e8ef2e2d32.png">

Also, this works
<img width="85" alt="Schermata 2020-07-25 alle 15 54 14" src="https://user-images.githubusercontent.com/43991400/88458541-19fede00-ce8f-11ea-9fce-4918792619fb.png">

And this works
<img width="91" alt="Schermata 2020-07-25 alle 15 54 47" src="https://user-images.githubusercontent.com/43991400/88458549-2be08100-ce8f-11ea-84d1-34ffa8fbec5f.png">

**Comment by sheaf** [comment]
Thanks for the bug report, this was a problem with the highlighter for quasiquotations. I've committed a fix to the repository and added a test case.

**Comment by gorilskij** [comment]
Thanks for the quick fix. I didn't know about quasiquoting at all, looks like an interesting feature of Haskell. Thanks for the theme recommendation too, I went with atom dark instead but highlighting infix operators is a nice idea.
