### ISSUE TITLE
Unicode Syntax `forall`

### ISSUE THREAD

**Issue by Meowcolm024** [JustusAdam/language-haskell#175]
<img width="510" alt="截圖 2020-11-02 下午12 58 28" src="https://user-images.githubusercontent.com/23007687/97833078-69b33800-1d0f-11eb-80c2-479cf187672d.png">

I find that the dot after the unicode `forall` is not highlighted with the same the "normal" one. 
Is it related to my theme (I'm using `Ayu Dark`) I'm using or is it a bug?
(I think it's not related to the ascii arrow on the left, as when chang it to the unicode one, the issue still occurs)

**Comment by sheaf** [comment]
Thanks for the report. This does seem to be a genuine bug, I'm looking into it.

**Comment by sheaf** [comment]
OK, should be fixed now.
