### ISSUE TITLE
Release unreleased changes?

### ISSUE THREAD

**Issue by vaclavsvejcar** [JustusAdam/language-haskell#180]
Hello @JustusAdam,

first of all, big thanks for the efforts you put into this extension, I use it daily and I'm really happy with it. Given the fact that there seems to be quite a lot of unreleased changes in [CHANGELOG.md](https://github.com/JustusAdam/language-haskell/blob/master/CHANGELOG.md), do you plan to release it any soon? I'm quite curious about the support for quasiquotation highlighting. Will it be actually possible to define highlighting rules for libraries such as [string-interpolate](https://hackage.haskell.org/package/string-interpolate) that for example following block of code:

```haskell
missingConfig desc yaml cli = [iii|
    Missing configuration for '#{desc}' (#{options}). See official documentation
    for more details: #{webDocConfigCurr}
  |]
```
would have the inside of `[iii|...|]` highlighted as string, the `#{` and `}` with some different style and the text inside `#{..}` as Haskell code, or that's beyond the possibilities of VSCode highlighting?

**Comment by sheaf** [comment]
That quasi-quotation would be given the `meta.embedded.block.iii` scope (on top of the usual `meta.quasi-quotation.haskell` scope), which should allow custom highlighting rules for the quasi-quote content.

**Comment by JustusAdam** [comment]
I apologize for my tardiness, the past few months have been quite busy. I'll see if I can make a release on the weekend.

Btw, @sheaf if you can figure out a way that I can give you release permissions on the marketplace I'd be happy to do so.

**Comment by JustusAdam** [comment]
Also I appreciate the compliment @vaclavsvejcar and I am happy to hear that you're enjoying this extension. But credit where credit is due, the latest fixes and additions are almost exclusively the work of @sheaf. I am very fortunate to have stumbled upon a second, very active maintainer.

**Comment by JustusAdam** [comment]
I pushed a release a few minutes ago, let me know if anything breaks
