### ISSUE TITLE
Incorrect Highlighting For Comments In Module Declaration

### ISSUE THREAD

**Issue by mizunashi-mana** [JustusAdam/language-haskell#2]
```haskell
module Main
  (
    -- * main func  <- disable highlighting
    main
    {- | disable, too
    -}
  ) where

-- enable comment highlighting
```

I think this is a miss.  However, there are not supported services such as GitHub.
So, possibly, this issue is not needed.

This issue seems to be caused by [textmate bundle](https://github.com/textmate/haskell.tmbundle), too.
Should I open an issue there?

**Comment by JustusAdam** [comment]
Yes I thing it is a good idea to report it there. I'd rather this be fixed in the bundle itself, because that'll benefit more people.
