### ISSUE TITLE
QuasiQuotes with immediate `|` are not parsed correctly

### ISSUE THREAD

**Issue by Martoon-00** [JustusAdam/language-haskell#203]
Calling a quasi-quoter as this breaks highlighting for me for all the following code:

```hs
[int||Text|]
```
![Screenshot from 2022-02-05 14-22-29](https://user-images.githubusercontent.com/5394217/152640079-149ac970-6f50-4623-b94d-1870296ddc62.png)

I saw a [commit](https://github.com/JustusAdam/language-haskell/commit/150c9c5c8ee943a2e67f593e400eeae29e17444a#) which is about a similar corner case - `[int||]`, but it works only if the second `|` is followed by `]`.

**Comment by Martoon-00** [comment]
I'm slowly starting to distribute the library where this fix is necessary, if that would be not hard, could I ask to release the recent changes? AFAIS the amount of pending changes there is not that small now.

**Comment by JustusAdam** [comment]
Sorry, I'll try to publish a release withing the next two weeks.
