### ISSUE TITLE
How to navigate to function definitions?

### ISSUE THREAD

**Issue by houseofwealth** [JustusAdam/language-haskell#205]
I'm running the Haskell Syntax Highlighting (3.4.0) in VS Code on linux, and its enabled. I have stack installed and on my path. When I open a haskell file, it shows the syntax highlighting but i cannot see how to navigate to function defs (even ones in the same file). When I right mouse click all I see is the standard VS code contextual menu options. Am I missing something obvious?

**Comment by JustusAdam** [comment]
Yes you are right. Since we know the scope of this extension in particular it makes sense to specify such in the README
