### ISSUE TITLE
Highlighting broken with version 3.5

### ISSUE THREAD

**Issue by ollimandoliini** [JustusAdam/language-haskell#208]
After upgrading to 3.5, syntax highlighting stopped working for me. I couldn't figure out how to access logs but am happy to provide them if given instructions.

I'm on:
- macOS 12.2.1
- Visual Studio Code 1.65.2

**Comment by theodornk** [comment]
Same

macOS  11.4
VScode 1.65

**Comment by livestalker** [comment]
Same

**Comment by paulpach** [comment]
Same here.  Downgraded to 3.4 and it works fine

**Comment by oskin1** [comment]
Same
macOS 12.1
VSCode 1.65.2

**Comment by why-not-try-calmer** [comment]
Same, 1.65.2, Linux x64 5.16.11

**Comment by KadenWolff** [comment]
Same. Spent an hour an hour trying to figure out what I did wrong, turns out I'm not alone. `Fedora 35`, `VSCode 1.65.2`

**Comment by MonsieurOrnix** [comment]
Hi ! Same for me.
Windows 10
VSCode 1.65.2

**Comment by Ptival** [comment]
For more details, it produces error messages:
```
Unable to load and parse grammar for scope text.tex.latex.haskell from file:///Users/val/.vscode/extensions/justusadam.language-haskell-3.5.0/syntaxes/literateHaskell.json Error: Unable to read file '/Users/val/.vscode/extensions/justusadam.language-haskell-3.5.0/syntaxes/literateHaskell.json' (Error: Unable to resolve nonexistent file '/Users/val/.vscode/extensions/justusadam.language-haskell-3.5.0/syntaxes/literateHaskell.json')
    at v.doReadFileStream (fileService.ts:573)
    at async v.doReadFile (fileService.ts:481)
    at async S.readExtensionResource (extensionResourceLoaderService.ts:36)
    at async Object.loadGrammar (TMGrammarFactory.ts:53)
```

**Comment by jbkroner** [comment]
Same issue, 
VScode 1.62.2
Windows 10

**Comment by BenoitRanque** [comment]
If you install both versions of the extensions, you will find that the files `syntaxes/haskell.json` and `syntaxes/cabal.json` are missing from 3.5. These can be copied from a 3.4 install and seem to work just fine

**Comment by MonsieurOrnix** [comment]
@BenoitRanque Your solution works for me. Thanks !

**Comment by ayoung19** [comment]
Following [this](https://stackoverflow.com/questions/42626065/vs-code-how-to-rollback-extension-install-specific-extension-version) stackoverflow post, I was able to get the syntax highlighting working by just installing version 3.4.

**Comment by kk-kien** [comment]
Downgrading to 3.4.0 works for me.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/101089509/158305561-2591d57b-e97a-4d91-98bb-ff951fcfd81c.png">
<img width="653" alt="image" src="https://user-images.githubusercontent.com/101089509/158305595-f0394928-7acc-4452-bd79-2d6a402a0a33.png">

**Comment by s0kil** [comment]
Also encountered this issue, downgrading solved it.

**Comment by why-not-try-calmer** [comment]
> If you install both versions of the extensions, you will find that the files `syntaxes/haskell.json` and `syntaxes/cabal.json` are missing from 3.5. These can be copied from a 3.4 install and seem to work just fine

That didn't do the trick for me. Only downgrading did.

**Comment by willbasky** [comment]
The same 
```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-15T10:06:23.022Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.11-2-MANJARO
```

**Comment by o1lo01ol1o** [comment]
Same; missing syntax files from the root `.vs-code` directory.

**Comment by AlexCQY** [comment]
same. Downgraded to `3.4` and works

**Comment by zacwood9** [comment]
Same here. Downgrading to 3.4 worked for me.

**Comment by ennioVisco** [comment]
Funny I just opened a Haskell project, and I haven't been programming in Haskell in years. I thought I screwed up my VS Code setup and reset everything, just to find out that it was an update from today that broke the syntax highlighting plugin 😅

**Comment by RentaroFuma** [comment]
Same issue
VScode 1.62.2
Windows 10

Сhangelog from the future?
![Screenshot_198](https://user-images.githubusercontent.com/87856495/158460875-3d3835e5-c026-46ce-9eef-f808544a303a.png)

**Comment by fuzzypixelz** [comment]
@JustusAdam thank you for the quick fix!

**Comment by KadenWolff** [comment]
@JustusAdam Thanks!

**Comment by MonsieurOrnix** [comment]
@JustusAdam Thank you !

**Comment by JustusAdam** [comment]
I appears that fixed it so I'm closing this now. Again sorry for breaking the extension and disrupting peoples workflow.

**Comment by why-not-try-calmer** [comment]
> This is what happens when you don't touch a project for a while and forget what the development workflow is ...
> 
> My apologies but it should be fixed now. Unfortunately vscode doesn't let me edit or unpublish a previous version so I had to create a new release.
> 
> I wish their publishing tool would emit a warning if there were files missing.

Wholehearted thanks for your work!

**Comment by Abastro** [comment]
Finally :)

**Comment by JustusAdam** [comment]
@TotallyNotChase what do you mean? Is 3.5 broken or 3.6? Which one were you running?

**Comment by TotallyNotChase** [comment]
> @TotallyNotChase what do you mean? Is 3.5 broken or 3.6? Which one were you running?

The open VSX registry seems to only have 3.6.0 after 3.3.0 - that's the one my vscode auto updated to and that's the one that broke the highlight. I rolled back to 3.3.0, I accidentally said I rolled back to 3.4.0 in my original comment.

**Comment by JustusAdam** [comment]
I am surprised, as I fixed the upload for 3.6 for the marketplace. I am unsure who currently does the upload to open VSX, but my guess is they made the same mistake I made with the marketplace upload in 3.5. 
I haven't yeat had a chance to look at open VSX myself and integrating uploads into my publishing pipeline so I'm afraid I will not be a ble to offer a fix for your issue in the short term. If you want to see this fixed you should contact the open VSX uploader for this package.

**Comment by joshuakb2** [comment]
I can corroborate that vscode-oss only has versions 3.0.3, 3.3, and 3.6, and that 3.6 is broken. Downgrading to 3.3 works for now.

**Comment by just-max** [comment]
FWIW, 3.6 from Open VSIX works for me, but only on a fresh VSCodium configuration OR after downgrading to 3.3 then upgrading again.
