### ISSUE TITLE
No autoindent after typing where, do etc

### ISSUE THREAD

**Issue by lemourin** [JustusAdam/language-haskell#21]
This commit introduces the issue: https://github.com/JustusAdam/language-haskell/commit/ac3ae6b42b29770eb2ab21aaab16efc209b4132f

According to this doc: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

vscode doesn't respect the field "indentationRules" in haskell-configuration.json, I just reverted the deletion of fields "main" and "activationEvents" in package.json and everything seems to work then.

**Comment by JustusAdam** [comment]
If you think you have identified the issue can you make a PR with those changes so that I may merge it? Thanks. :)
