### ISSUE TITLE
Binding patterns named `pattern` are recognized as a keyword

### ISSUE THREAD

**Issue by MatthijsBlom** [JustusAdam/language-haskell#216]
Witness,

```haskell
_ = case () of
  pattern         -> ()
  pattern@pattern -> ()
  -- Constrast
  name            -> ()
  name@pattern    -> ()
```

&hellip;Apparently GitHub has a similar problem.

VSCode reports scope `source.haskell` in the bottom two lines, but additionally `keyword.other.pattern.haskell` and `meta.declaration.pattern.haskell` in the upper two.

**Comment by JustusAdam** [comment]
That's because `patttern` is a GHC keyword and the parser cannot detect whether or not you have the GHC extension enabled that makes `pattern` a keyword. I'm afraid we can't fix this one.
