### ISSUE TITLE
QuasiQuotes

### ISSUE THREAD

**Issue by dpwiz** [JustusAdam/language-haskell#23]
They can mean just about anything so their contents should be treated either as plain text or a string literal.

There is a [list of reserved names](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#template-haskell-quasi-quotation) for quotes that should remain as Haskell code.

**Comment by marcotoniut** [comment]
It would be nice if language-haskell would somehow allow for extended syntax highlighting on QuasiQuote expressions.

**Comment by vaclavsvejcar** [comment]
Wondering if there are any plans for this issue? Any chance to have quasiquotes somehow visually distinguished?

**Comment by JustusAdam** [comment]
My intuition is that it is possible, but I don't have the time to work on it. If you want to give it a shot go ahead.

AFAIK there are standard quasi quoters for declarations and expressions. A multi line matcher could be used for the quote brackets and then an include for the expression or declaration rules would add the desired highlighting.

**Comment by poscat0x04** [comment]
Right now QuasiQuotes are incorrectly linted if there are keywords in it.

**Comment by nilehmann** [comment]
Hi, I'm dealing with the same problem. Why is this marked as enhancement and not as bug?

**Comment by sheaf** [comment]
I've made a simple change so that the entire quasi-quotation is only given the `meta.quasi-quotation` scope, with no Haskell highlighting.

The "enhancement" part of the bug pertained to the ability to highlight the inside of the quasi-quote depending on the quasi-quoter, e.g. highlight a JSON quasi-quotation using JSON rules, or highlight the different types of Haskell quasi-quotations (type/expression/etc) using the appropriate rules.

**Comment by nilehmann** [comment]
@sheaf, that makes sense. And thank you for implementing the quick fix :smiley:, the highlighting inside of quasiquotes was killing me.

**Comment by sheaf** [comment]
I also implemented simple Haskell highlighting for the expression, pattern, declaration and type quasi-quoters. Anything more than that starts getting a bit tricky unfortunately.

**Comment by nilehmann** [comment]
Should 3.1.0 have these changes? I just updated but I don't see any of the new scopes :S. What could I be doing wrong?

**Comment by sheaf** [comment]
The changes are indeed part of 3.1.0. (I just checked to confirm).
![quasiquote-scopes](https://user-images.githubusercontent.com/1297748/81593770-3925bd80-93c0-11ea-9822-1c57cdfe0276.png)

If you press Ctrl+Shift+P and bring up `Developer: Inspect Editor Tokens and Scopes`, you should see the `meta.quasi-quotation.haskell` scope over the whole quasi quotation, and then the appropriate highlighting in case it's a Haskell quasi-quotation.

**Comment by nilehmann** [comment]
Yeah, I was exactly doing that and I didn't see the scope. There's must be something on my end (maybe conflicting with another extension?). I'll try with a clean vscode setup when I have time and see...

**Comment by sheaf** [comment]
The other thing you can do is manually revert to an older extension (`Install another version...` after pressing the settings gear next to the extension in the list of extensions), and then update again to 3.1.0.

**Comment by JustusAdam** [comment]
Ah that's my fault. Apparently I forgot to rebuild the JSON before publishing. I really need to make that automatic.

**Comment by nilehmann** [comment]
Yup, working for me in 3.2.0 now. On the bright side I learn a lot about scopes, textmate and stuffs along the way :grin:

**Comment by JustusAdam** [comment]
Run while you still can :stuck_out_tongue_closed_eyes: :laughing:

**Comment by jbpotonnier** [comment]
Would it be possible to mark the quasi quote content with the scope `meta.embedded.block.{nameOfQuasiQuote}` ?

For example, the content of 
```haskell
[hsx|
        <div>
        ...
        </div>
    |]```

would be marked as `meta.embedded.block.hsx}`

If I got it correctly, it would then be possible to provide separate extensions for any quasiquote syntax.

**Comment by sheaf** [comment]
@jbpotonnier Thanks for the suggestion, which I've implemented in 4c9905e. So we have:

```haskell
[hsx| ... |]
      ^^^ meta.embedded.block.hsx

[Qualifier.hsx| ... |]
                ^^^ meta.embedded.block.hsx
```

Let me know if that works for you.

**Comment by poscat0x04** [comment]
Currently, quasi-quotations will break the linting of codes after it if there are no letters in between the parenthesis:
![image](https://user-images.githubusercontent.com/53291983/101613070-4a15da80-3a46-11eb-8626-662b7500743f.png)
![image](https://user-images.githubusercontent.com/53291983/101613124-5732c980-3a46-11eb-8216-f756cfa4c04a.png)

**Comment by sheaf** [comment]
@poscat0x04 Fixed the issue with empty quasi-quotations in 150c9c5, thanks for the bug report.
