### ISSUE TITLE
Incorrect Highlighting to Comments

### ISSUE THREAD

**Issue by TheCongaGuy** [JustusAdam/language-haskell#233]
At the top of my project, I have a comment formatted as:

-- {{Course Number}} - {{Current Semester}} -- {{Assignment}} - {{Programming Language}}

The syntax highlighting reads this as an attempt to access a file. The resulting warning message is:

{{Drive}}:\{{My PC}}\{{Me}}\{{Application}}\Local\ghcide\main-da39a3ee5e6b4b0d3255bfef95601890afd80709\ext4356: renameFile:renamePath:MoveFileEx "\\\\?\\{{Drive}}:\\{{My PC}}\\{{Me}}\\{{Application}}\\Local\\ghcide\\main-da39a3ee5e6b4b0d3255bfef95601890afd80709\\ext4356" Just "\\\\?\\{Drive}:\\{{My PC}}\\{{Me}}\\{{Application}}\\Local\\ghcide\\main-da39a3ee5e6b4b0d3255bfef95601890afd80709\\{{Assignment}}.hie": permission denied (Access is denied.)compiler

It seems up to chance for this warning to pop up. Sometimes it does, other times it doesn't, but it is always underlining this comment. The project still compiles and runs, but the warning always gives me a scare.

**Comment by JustusAdam** [comment]
Oh, that is indeed weird. My guess however is that this should not be our extension as it only provides syntax highlighting. Do you have any sort of Haskell IDE running? Perhaps you installed this https://marketplace.visualstudio.com/items?itemName=haskell.haskell?

**Comment by TheCongaGuy** [comment]
Oh it was my impression that the syntax highlighting would be highlighting any errors that crop up! I do indeed have that extension on VSCode; I'll submit an issue with them instead. Sorry about that!

**Comment by JustusAdam** [comment]
No worries, glad I could help. Best of luck with finding a fix!
