### ISSUE TITLE
Incorrect comments in literate Haskell files

### ISSUE THREAD

**Issue by sjorn3** [JustusAdam/language-haskell#24]
When making automatic line comments inside of a literate file, the Haskell comments are used, but should be the latex style comments (in my case).

```haskell
> main = do

becomes

-- > main = do

rather than

% > main = do
```

Am I just doing something wrong? Let me know.

**Comment by JustusAdam** [comment]
Yes. Because the comments are defined in a language configuration file. And lhs and hs use the same configuration file. Perhaps I could use a different one for lhs, that might fix it.
