### ISSUE TITLE
Getting rid of the snippets

### ISSUE THREAD

**Issue by Eugleo** [JustusAdam/language-haskell#25]
Users can define their own snippets of code easily in VSCode, so I think the provided snippets are not needed. I personally don't use all of them and so they are mostly just annoyingly appearing, because there is no way to turn them off.

**Comment by glchapman** [comment]
Sorry to comment on a closed issue, but you should also update the description on the VS Code Marketplace to remove the section on Snippets (or possibly change the section to state that they have been removed).

**Comment by JustusAdam** [comment]
Thanks for the reminder. I forgot about that.
