### ISSUE TITLE
Type signatures in do bindings classed as top level definitions, removing (<-) highlighting

### ISSUE THREAD

**Issue by tomsmalley** [JustusAdam/language-haskell#28]
<img width="196" alt="screen shot 2017-06-25 at 15 55 27" src="https://user-images.githubusercontent.com/4387499/27517162-93327144-59bf-11e7-84c5-ef1b8bdf8484.png">

This behaviour is not observed when the part to the left of (<-) is wrapped in parenthesis.

**Comment by JustusAdam** [comment]
Should be easy to fix. Look for the section where type signatures are defined (search for the `::` in the grammar). And there is a bunch of patterns defined for when it should stop (such as `}` and `)`) just add `<-` and that'll probably do it.
