### ISSUE TITLE
Qualified infix functions incorrectly highlighted

### ISSUE THREAD

**Issue by tomsmalley** [JustusAdam/language-haskell#30]
<img width="206" alt="screen shot 2017-06-26 at 11 00 53" src="https://user-images.githubusercontent.com/4387499/27534434-e57b5a52-5a5e-11e7-89c6-1c4116fcd1ba.png">

Sorry for making so many issues, I just started using vscode and I'm just reporting things as I come across them. I can collect them into a single issue in future if you would prefer, since they are all very minor issues.

**Comment by JustusAdam** [comment]
I have noticed the same thing before. I'll have a look at it when I get the time, you can try yourself too.
