### ISSUE TITLE
Support for Code Outline

### ISSUE THREAD

**Issue by W4RH4WK** [JustusAdam/language-haskell#33]
Are you thinking about supporting the [code outline extension](https://github.com/patrys/vscode-code-outline)?

**Comment by JustusAdam** [comment]
I didn't even know that extension existed.
I'm not sure. How good is the extension? How stable is its api and how does it even work? What would be necessary to support it?

**Comment by W4RH4WK** [comment]
I have looked at this extension in more detail now. First I thought one had to register symbols directly with this extension. However, it turns out that it uses the symbols of a file registered in VSCode. The same list, which is used when hitting `ctrl + t`.

As this extension is only about Haskell syntax highlighting, this feature goes beyond its scope. I'll ask the guys responsible for the Haskero extension about this feature.
