### ISSUE TITLE
KindSignatures and `data` keyword don't mix

### ISSUE THREAD

**Issue by vapourismo** [JustusAdam/language-haskell#35]
![screenshot](http://i.imgur.com/IbhRVsa.png)

Works without kind signature.

It would be sufficient if `data` is treated as a keyword in case `data TypeName (=|where)` doesn't match.

**Comment by JustusAdam** [comment]
I think a better idea would be to actually recognize and highlight the kind singnature.

**Comment by sheaf** [comment]
In a similar vein:
![gadt_kind_signature](https://user-images.githubusercontent.com/1297748/47997330-bf8e7e80-e0fb-11e8-83d9-67d6f8797ba7.png)
