### ISSUE TITLE
Please highlight equal signs and other important characters

### ISSUE THREAD

**Issue by btipling** [JustusAdam/language-haskell#36]
Thank you for making and maintaining this plugin! If you look at how GitHub displays blocks like this:

```haskell
foobar = let
    foo = bar
    fuzz = buzz
    test = tested
    in (finalResponse)
```
you can see that the equal sign is highlighted. Without at least the equal sign being highlighted I have big blocks of entirely plain text code with no syntax highlighting at all. 

I also recommend highlighting the `$` operator.

```haskell
foo = bar $ some thing
```

And  `++` as well.

```haskell
foo = "concated a " ++ "string"
```

It just seems like a lot of basic things aren't highlighted.

![image](https://user-images.githubusercontent.com/249641/27965210-e38b10c2-62ef-11e7-8744-57088a93420a.png)

**Comment by JustusAdam** [comment]
Hi, thanks for the praise.

Unfortunately your issue is not with the plugin, but the color theme.
I use the "monokai" theme for instance and for me **all** operators, including `=` are highlighted.
I cannot decide what is highlighted and what isn't, I can only assign meaning to things in the code by assigning tags to them. The color theme decides which tags it highlights and which it doesn't.

**Comment by btipling** [comment]
Thank you. I didn't realize it was a theme issue.

**Comment by JustusAdam** [comment]
I don't know how it works in vscode, but I remember in atom you had a user stylesheet and you could use it to alter the code highlighting. you could even do so for specific languages only by using the appropriate css classes.
Perhaps you could use that approach if you are attached to your theme.

**Comment by monk-time** [comment]
> Unfortunately your issue is not with the plugin, but the color theme.
> I use the "monokai" theme for instance and for me **all** operators, including `=` are highlighted.
> I cannot decide what is highlighted and what isn't, I can only assign meaning to things in the code by assigning tags to them. The color theme decides which tags it highlights and which it doesn't.

I have the same issue, and I believe it does stem from how this plugin defines scopes.  When I use "Developer: Inspect TM Scopes", I can see that the equal sign is marked as `keyword`, whereas usually (with a default light or dark theme in python and js files) it belongs to `keyword.operator`. 

I would love to be able to redefine the highlighting for `=` and similar symbols manually, but the plugin lacks specific scopes that would allow me doing that. E.g., I prefer to keep keywords bolded, but with the plugin scopes it makes `=`  bold too, which looks just silly. 

Could it be possible to re-open this issue?

**Comment by JustusAdam** [comment]
Feel free to experiment with the scopes.

If you submit a PR for a scope change that either

- does not change the current representation across the popular themes
- or changes them in a sensible way

I'll merge it.
