### ISSUE TITLE
String "^\\" causes improper highlighting

### ISSUE THREAD

**Issue by JayDepp** [JustusAdam/language-haskell#43]
The string `"^\\"` causes the end quote to not be recognized.

![image](https://user-images.githubusercontent.com/17534694/29435868-d431ba34-8376-11e7-904f-001a8af0a0b8.png)

**Comment by JustusAdam** [comment]
I found the bug and fixed it. But my publishing setup is broken right now. I'll publish it as soon as I can fix it.
