### ISSUE TITLE
Option to disable auto-indent.

### ISSUE THREAD

**Issue by scott-fleischman** [JustusAdam/language-haskell#46]
I am finding I am undoing the indent a lot of the time. It would be nice to have an option to disable it from happening.

Disabling `editor.autoIndent` for `haskell` in the user settings seems to avoid some of the instances (such as auto-indenting when pasting) but some basic ones still occur (such as hitting `Enter` and having it indent too far).

```
  "[haskell]": {
    "editor.autoIndent": false
  },
```

**Comment by JustusAdam** [comment]
I don't know how much control the extension has about this.
The only non-default setting this extension uses is to redefine when to indent but not *whether*.
