### ISSUE TITLE
Markdown Fenced Code Block Grammar Injection

### ISSUE THREAD

**Issue by chisui** [JustusAdam/language-haskell#48]
It would be nice if hightlighting would work on fenced markdown code blocks like this

    ```haskell
    myhaskell code
    ```

here is an [example](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example) of how to do this.

**Comment by glebec** [comment]
I would also like the language alias `hs` to work with this, in addition to (not instead of) `haskell`.

**Comment by JustusAdam** [comment]
Feel free to open a PR for this.

**Comment by glebec** [comment]
I have it working locally with `haskell` blocks. Going to add `hs`, `cabal`, etc., polish it up and submit a PR. Expect to see it soonish (maybe today).

**Comment by glebec** [comment]
Update: working `haskell` / `hs` is demonstrated in [this diff on my fork](https://github.com/glebec/language-haskell/compare/glebec:d61be4...148a2f2).

However I'm having unexpected difficulties with doing the same for literate haskell and cabal.  As mentioned in a call-to-aid I left [here](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example/issues/5#issuecomment-387255565), I have a [separate branch](https://github.com/glebec/language-haskell/compare/d61be4ddaff7...demo/failing-cabal) that attempts (but fails) to add Cabal support.

I'm not sure why it is failing and I have other priorities at the moment, so I'm going to leave these notes here for a little while in the hopes of hearing back from the author of the grammar injection template. If this gets stale, others will at least be able to pick up where I left off, but hopefully I'll be able to get this ironed out soon and this comment will become moot.

**Comment by JustusAdam** [comment]
Feel free to push only the `haskell`/`hs` support for now and we can worry about cabal and literate haskell later?

**Comment by glebec** [comment]
@mjbvz helped me to debug the cabal issue, which was just an oversight on my part. Full support now provided by #56.
