### ISSUE TITLE
Parsing confused by type-level string (Symbol)

### ISSUE THREAD

**Issue by jchia** [JustusAdam/language-haskell#50]
The following code snippet is parsed incorrectly. The last two lines for `main` are completely unhighlighted in the vscode editor. The problem goes away if `"of"` is changed to `"f"`. I'm running language-haskell 2.4.0 on vscode 1.19.0 with ghc 8.2.2.

    {-# LANGUAGE DataKinds, FlexibleInstances, KindSignatures, MultiParamTypeClasses, FunctionalDependencies #-}

    import GHC.TypeLits

    data Label (l :: Symbol) = Get

    class Has a l b | a l -> b where
      from :: a -> Label l -> b

    data Point = Point Int Int deriving Show

    instance Has Point "of" Int where from (Point x _) _ = x

    example = from (Point 1 2) (Get :: Label "of")

    main :: IO ()
    main = undefined

**Comment by JustusAdam** [comment]
Also I am noticing that attaching the kind signature to the `l` type parameter makes the `data` keyword not work.
