### ISSUE TITLE
Maybe consider switching to json?

### ISSUE THREAD

**Issue by shayne-fletcher-da** [JustusAdam/language-haskell#62]
It seems VS code recommend .json for tmLanguage grammars. I used [this extension](https://marketplace.visualstudio.com/items?itemName=Togusa09.tmlanguage) to convert and it seems to work, if you decide in future to switch. Just friendly sharing knowledge - not suggesting you must! :)

**Comment by JustusAdam** [comment]
I'm not a fan of plists either. If you do the conversion and make sure it works I'll gladly accept a pull request.

PS there are test `.hs` files in the repo which are supposed to cover most syntactic cases. If they look the same after converting it should be fine.

**Comment by JustusAdam** [comment]
Due to the limitations of the JSON grammars (particularly with respect to comments) this issue is officially closed. Perhaps at some point in the future we can substitute a different file format, with less limitations, and generate the plist or json from it.
