### ISSUE TITLE
Comment before module "where" isn't shown as comment

### ISSUE THREAD

**Issue by runeksvendsen** [JustusAdam/language-haskell#64]
<img width="248" alt="screen shot 2018-09-17 at 13 15 32" src="https://user-images.githubusercontent.com/1069247/45620083-dc072680-ba7b-11e8-815b-ccdb0a6da502.png">

See attached screenshot. Syntax highlighting for the first comment is broken for this snippet:

```haskell
module Test
-- This is a comment
where
-- This is a comment

import Etc
```

**Comment by JustusAdam** [comment]
Should be fixed with 733f56169c446e9dbd2c5915fbdcb3e445160198
