### ISSUE TITLE
Hash symbol at end of identifier should inherit highlighting

### ISSUE THREAD

**Issue by sheaf** [JustusAdam/language-haskell#67]
The magic hash character, i.e. a hash sign at the end of an identifier, should be highlighted like the identifier that it is appended to. This should also apply to multiple hashes in a row.

![magic_hash](https://user-images.githubusercontent.com/1297748/47997444-20b65200-e0fc-11e8-9556-c96719c4f681.png)

**Comment by JustusAdam** [comment]
See I am not sure about that one. Is `#` not also a valid operator? I think when `MagicHash` is not enabled code such as `func#` is not an identifier but actually `func #`.

**Comment by sheaf** [comment]
Yes, to be completely correct it would be necessary to know whether MagicHash is enabled or not.
Assuming that's not doable with the way syntax highlighting works in VS Code, I personally think that highlighting as if the extension was turned on yields better results (in spite of MagicHash not being a common extension to use!), because you can add spaces in the situation you describe to get the correct result, whereas there is no way to get the highlighting to look correct in the example I gave.

**Comment by JustusAdam** [comment]
> because you can add spaces in the situation you describe to get the correct result

While that is true I worry that beginners in particular might get confused by the highlighting. As you rightly pointed out `MagicHash` is not a common extension.

Ideally I would like there to be a switch in the config that one could flick to enable/disable highlighting `#` as identifier or operator. I wonder if that is possible. (It probably is but the question is if it is reasonably easy)

**Comment by sheaf** [comment]
I've added opt-in highlighting for magic hash in e9e1b38. Any use of `#` falls under the `keyword.operator` scope, but when it's a magic hash it gets a scope of either:
  - `keyword.operator.postfix.hash` when it is detected as a postfix magic hash,
  - `keyword.operator.hash` when it is used in an unboxed tuple.

So by default it'll use the `keyword.operator` scope and highlight as any other operator, but if the user sets specific colours for `keyword.operator.postfix.hash` and `keyword.operator.hash`, they can highlight it differently. Unfortunately it's not reasonable with this approach to allow the highlighting to depend on the situation, but I think it still looks pretty good:

![magic_hash_highlighting](https://user-images.githubusercontent.com/1297748/81251017-a0d7b380-9022-11ea-84cf-f078ba8f7ec6.png)
