### ISSUE TITLE
Nested parentheses in imports/exports are not parsed correctly

### ISSUE THREAD

**Issue by sheaf** [JustusAdam/language-haskell#69]
See for instance:
![parentheses_in_imports_and_exports](https://user-images.githubusercontent.com/1297748/47997748-3b3cfb00-e0fd-11e8-9690-d9fa1720a6f7.png)

**Comment by JustusAdam** [comment]
So it seems to me there are at least two problems here.

1. at least in export lists numbers are not considered part of a functions name
2. Export lists are prematurely terminated in the presence of a closing paren. This does not change with the addition or removal of a newline.

**Comment by aryairani** [comment]
Same here:

Good code, bad parse:
![image](https://user-images.githubusercontent.com/538571/58291745-83b3c180-7d8c-11e9-9bde-cab2de574743.png)

vs bad code, good parse?  (improperly deleted last char of 3rd line)

![image](https://user-images.githubusercontent.com/538571/58291760-94fcce00-7d8c-11e9-9542-44f3f150d763.png)
