### ISSUE TITLE
Missing keywords: data and type families, pattern synonyms, deriving via

### ISSUE THREAD

**Issue by sheaf** [JustusAdam/language-haskell#72]
Here are some examples of missing keywords:

the keywords "family", "instance" and "where" in type/data families, e.g.:
![type family](https://user-images.githubusercontent.com/1297748/47998457-ad164400-e0ff-11e8-9486-60ec9cd5a15c.png)
![open_type_family](https://user-images.githubusercontent.com/1297748/47998500-d040f380-e0ff-11e8-88fe-e2af937834d6.png)

"via" from the deriving via extension:
![deriving_via_keyword](https://user-images.githubusercontent.com/1297748/47998267-fade7c80-e0fe-11e8-9cb5-0d6ea5efa3d0.Png)
(Note also that the type variable in the standalone deriving declaration is not highlighted correctly.)

"pattern" for a pattern synonym declaration
![pattern_synonyms](https://user-images.githubusercontent.com/1297748/47998479-bf907d80-e0ff-11e8-8ca0-fee51249e8f7.png)

**Comment by sheaf** [comment]
Excellent, the addition of highlighting for type families and pattern synonyms is very much appreciated. Thanks!

The code for highlighting type families should be extended to work with data families too:
![data_family_highlighting](https://user-images.githubusercontent.com/1297748/80318417-452f4e00-880a-11ea-9066-49965fdbadce.png)
Changing `data` to `type` in the above makes the highlighting work properly, so it seems it's just a case of allowing the `data` keyword.

For pattern synonyms, multiple patterns are not currently highlighted properly:
![multiple_pattern_synonyms_highlighting](https://user-images.githubusercontent.com/1297748/80318519-0b127c00-880b-11ea-9ea6-6496508b41d2.png)
If that's annoying to fix then no big deal of course. (I'm not sure why `False` is not getting highlighted properly there BTW.)

As seen in this screenshot, it would also be nice to support the keywords for the three built-in deriving strategies: `stock`, `newtype` and `anyclass`. 

Finally, the highlighting for the single-line deriving via that is currently implemented seems to always require parentheses:
![deriving_via_highlighting](https://user-images.githubusercontent.com/1297748/80318707-3f3a6c80-880c-11ea-85fe-7606aac97343.png)

Sorry for including all this in this single ticket; I can split it out into other issues if you would prefer.    
I have a few other bugs to report, but let me be clear that I am very appreciative of the effort you have put in, and don't in any way mean to discourage. Thanks again.

**Comment by sheaf** [comment]
I realise now that defining multiple patterns at once in a pattern synonym is actually already supported, but it's #122 that makes it look otherwise.

**Comment by JustusAdam** [comment]
Okay, I think I got them all now?

Thanks for the diligent reporting!

**Comment by sheaf** [comment]
All the keywords mentioned in this ticket are now supported, so I'm closing this issue.

Some highlighting issues still remain, e.g. type families aren't correctly highlighting types (highlighting them as values instead). This is being tracked separately in #133.
