### ISSUE TITLE
Support for `::` appearing on the following line

### ISSUE THREAD

**Issue by CaptJakk** [JustusAdam/language-haskell#83]
Right now, the highlighter conveniently colors type declarations when it is followed by `::` on the same line. However this feature does not hold for when the `::` is on the following line. This is unfortunate because if you have large type signatures, brittany and other source formatters will put the type assertion on the line following the name of the definition. Which causes the syntax highlighting of the type signature to not remotely resemble what it would for a one-line type sig. I am not sure how much work this is but I figured I'd cut the issue to track it and possibly solicit advice on either fixes or workarounds for this.

**Comment by JustusAdam** [comment]
I don't think this problem is fixable. The grammar framework that the highlighting uses is very restrictive. It's not really possible to distinguish between a new function name and a Template Haskell invocation I think.

**Comment by eddiemundo** [comment]
I experimented a bit and I think this might be possible. Not sure if this works with what already exists, but the idea is to use `::` and `.*=` to delimit a scope. Here's the file
```json
{
  "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  "name": "haskelltest",
  "patterns": [
    {
      "include": "#type-declaration"
    }
  ],
  "repository": {
    "type-declaration": {
      "begin": "::",
      "end": ".*=",
      "beginCaptures": {
        "0": { "name": "keyword.type.haskelltest" }
      },
      "contentName": "keyword.type.haskelltest",
      "patterns": []
    }
  },
  "scopeName": "source.hstest"
}
```
which gives the below result
![Screenshot from 2019-05-23 00-09-49](https://user-images.githubusercontent.com/929157/58225300-5e24aa80-7cef-11e9-8ab1-5b0c2aa08f4e.png)

**Comment by eddiemundo** [comment]
Nevermind this idea is too simple. Doesn't cover guards, and I can't think of a way of doing it.

**Comment by JustusAdam** [comment]
Yeah and also there's template haskell 😅 which means that you may have a completely undelimited top-level value
