### ISSUE TITLE
Typing 'null' unindents a line

### ISSUE THREAD

**Issue by dramforever** [JustusAdam/language-haskell#86]
## Steps to reproduce:

Type this into vscode:

```
x =
    null
```

**Actual behavior**: The line containing `null` gets unindented

**Expected behavior**: Function body remains indented

This also happens if the line is not just null but, say, `not (null xs)` and you're typing the `null` part inside of it

**Comment by JustusAdam** [comment]
😂 

I know what the reason is and it's just too funny.
