### ISSUE TITLE
Identifier with umlaut

### ISSUE THREAD

**Issue by Joel-Speitelsbach** [JustusAdam/language-haskell#88]
An identifier with an umlaut is not recognized correctly. 

```
schönheit = undefined

hasNoUmlaut = undefined
```

Click on one of the two identifiers and start the command `addSelectionToNextFindMatch` (ctrl-d).

I'm a German dude, so i notice it with Ä,ä,Ü,ü,Ö,ö,ß, but characters like â,à,á have the same issue.

It seems to be an regression from 2.5.0 to 2.6.0. 

What is your guess from where this behavior arises? (If you like, I could have a brief look there.)

**Comment by JustusAdam** [comment]
I'm a german dude too, but I have never actually written german code 😄

I think this should be easy to fix by simply amending the identifier character matches. I won't have the time anytime soon, so if this is a big issue for you then probably best do it yourself, I'll gladly accept a PR.

**Comment by JustusAdam** [comment]
This seems to work now? At least for top-level identifiers this seems to work in my instance. Please let me know if it is still an issue for you, then I will reopen this issue.

**Comment by Joel-Speitelsbach** [comment]
Yes it works now! Amazing.

**Comment by JustusAdam** [comment]
I think this was a vscode issue actually. It's nice they fixed that now :smile:
