### ISSUE TITLE
autoClosing for single quotes

### ISSUE THREAD

**Issue by HuwCampbell** [JustusAdam/language-haskell#9]
I'm not sure this should be in haskell-configuration.json as although single quotes are used for literals, they're more often used as primes and data kind ticks.

Having to constantly delete the second prime is annoying.

**Comment by JustusAdam** [comment]
A, good point. I didn't think about that. Yes I think its a sensible idea to remove it again.

**Comment by JustusAdam** [comment]
Published with version 1.4.3
