### ISSUE TITLE
Typeclasses with exactly one declaration don't highlight properly

### ISSUE THREAD

**Issue by Jeremy-Stafford** [JustusAdam/language-haskell#91]
Type-class definitions with exactly one declaration 'take over' the remainder of the file:
![image](https://user-images.githubusercontent.com/36511199/58463822-76039080-812c-11e9-967a-ca4891662aab.png)
This does not happen if there is (literally) anything on the next line:
![image](https://user-images.githubusercontent.com/36511199/58463955-bc58ef80-812c-11e9-839e-057bd1255679.png)
It also does not happen for type-classes with no declarations:
![image](https://user-images.githubusercontent.com/36511199/58464050-e90d0700-812c-11e9-9b83-a7a90383fde6.png)

**Comment by JustusAdam** [comment]
Weird, I cannot reproduce that behaviour.

When I tried it it worked. Both with an empty line, and even if there was not space in between at all.

<img width="196" alt="Captura de pantalla 2019-06-05 a las 12 08 25 a  m" src="https://user-images.githubusercontent.com/5824532/58917222-2e7d9580-8726-11e9-9759-c278dc6d9532.png">

<img width="190" alt="Captura de pantalla 2019-06-05 a las 12 08 17 a  m" src="https://user-images.githubusercontent.com/5824532/58917231-33424980-8726-11e9-88be-807ad0f9e728.png">

**Comment by Jeremy-Stafford** [comment]
After a bit of testing, I have discovered that it works so long as the `module` block is not indented, as is quite a common style. However, if it is indented, then it does not work. This is also true for GADTs:
![image](https://user-images.githubusercontent.com/36511199/59123870-31f76380-8956-11e9-81be-baf54337a5da.png)

![image](https://user-images.githubusercontent.com/36511199/59123912-49365100-8956-11e9-94db-11b07cf8d912.png)

This is probably because most people do not indent `module` blocks, so this should probably become a feature rather than a bug (eg, 'add support for indented `module` blocks').

**Comment by JustusAdam** [comment]
Turns out this was actually a bug in the matcher for when a type annotation ends and thus a more general problem
