### ISSUE TITLE
Can't seem to disable autoindentation?

### ISSUE THREAD

**Issue by edsko** [JustusAdam/language-haskell#98]
I have set

```
    "editor.autoIndent": false,
```

as well as

```
    "haskell.indentationRules.enabled": false
```

but it still tries to be smart about indentation. I'd prefer it would just copy the indentation from the previous line.

**Comment by edsko** [comment]
It turns out it works partially...? After

```
instance Eq Int where
```

I do get indentation with these enabled, and no indentation with it disabled, as expected. But after

```
data T = T {
```

I get indentation no matter what..?

**Comment by JustusAdam** [comment]
Well, the indentation after `where` for instance is from our indentation rules, but I suspect the one after `{` comes from the fact that `{}`, `[]` and `()` is listed as `brackets` in the json config and I don't think there's an easy way to disable indenting after that.

**Comment by edsko** [comment]
The new (in relation to this ticket..) `keep` auto-indent mode fixes this. (Though somewhat related: https://github.com/microsoft/vscode/issues/125261).
